 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: HPA                                                         
     # Surfaces =   5
     # Strips   =  64
     # Vortices = 410

  Sref =  22915.       Cref =  30.500       Bref =  1095.5    
  Xref =  15.000       Yref =  0.0000       Zref = 0.50000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.20299     Cltot =  -0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.06091
  CZtot =  -1.67723     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.68915
  CDtot =   0.03241
  CDvis =   0.02000     CDind = 0.0124125
  CLff  =   1.69635     CDff  = 0.0132302    | Trefftz
  CYff  =  -0.00000         e =    1.3220    | Plane  

   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   7.043880    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.438175
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.220456
 y  mom.  Cm |    Cma =  -1.764194    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.012158

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   4.314769    CLr =  -0.000000
 y  force CY |    CYp =  -0.328604    CYq =   0.000000    CYr =   0.313684
 x' mom.  Cl'|    Clp =  -0.805876    Clq =  -0.000000    Clr =   0.407805
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -25.740810    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.186548    Cnq =  -0.000000    Cnr =  -0.028910

                  elevator     d1     rudder       d2 
                  ----------------    ----------------
 z' force CL |   CLd1 =   0.006028   CLd2 =  -0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.004463
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000028
 y  mom.  Cm |   Cmd1 =  -0.034943   Cmd2 =  -0.000000
 z' mom.  Cn'|   Cnd1 =   0.000000   Cnd2 =   0.000860
 Trefftz drag| CDffd1 =  -0.000380 CDffd2 =   0.000000
 span eff.   |    ed1 =   0.047439    ed2 =  -0.000000



 Neutral point  Xnp =  22.638958

 Clb Cnr / Clr Cnb  =   1.285456    (  > 1 if spirally stable )
